import { Sparkles, ThumbsUp, ThumbsDown } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import type { ReviewSummary } from "@/features/ai/review-summary";

export function ReviewSummaryCard({ summary }: { summary: ReviewSummary }) {
  return (
    <Card className="border-purple-200 bg-gradient-to-br from-purple-50 to-indigo-50 dark:border-purple-900/40 dark:from-purple-950/20 dark:to-indigo-950/20">
      <CardContent className="space-y-3 p-5">
        <div className="flex items-center gap-2">
          <span className="flex h-6 w-6 items-center justify-center rounded-md bg-gradient-to-br from-purple-600 to-indigo-600 text-white">
            <Sparkles className="h-3.5 w-3.5" />
          </span>
          <p className="text-sm font-semibold">AI review summary</p>
        </div>

        <p className="text-sm">{summary.headline}</p>

        <div className="grid gap-3 sm:grid-cols-2">
          {summary.pros.length > 0 ? (
            <div>
              <p className="mb-1 flex items-center gap-1 text-xs font-semibold text-emerald-600">
                <ThumbsUp className="h-3 w-3" /> What people like
              </p>
              <ul className="space-y-0.5">
                {summary.pros.map((p) => (
                  <li key={p} className="text-xs text-muted-foreground">• {p}</li>
                ))}
              </ul>
            </div>
          ) : null}

          {summary.cons.length > 0 ? (
            <div>
              <p className="mb-1 flex items-center gap-1 text-xs font-semibold text-rose-600">
                <ThumbsDown className="h-3 w-3" /> Watch-outs
              </p>
              <ul className="space-y-0.5">
                {summary.cons.map((c) => (
                  <li key={c} className="text-xs text-muted-foreground">• {c}</li>
                ))}
              </ul>
            </div>
          ) : null}
        </div>

        <p className="text-[10px] text-muted-foreground">Generated by AI from verified reviews.</p>
      </CardContent>
    </Card>
  );
}
